### ISSUE TITLE
Use Payload instead of Message

### ISSUE THREAD

**Issue by b-viguier** [amphp/http-client#158]
Since version `1.3.0` the `byte-stream` has deprecated `Message` class in favor of `Payload`.
https://github.com/amphp/byte-stream/releases/tag/v1.3.0

Artax should be updated to use this new class.

-----
PS: thanks for you work!

**Comment by kelunik** [comment]
@b-viguier It will be updated in the next major version. There's no immediate need to upgrade.

**Comment by kelunik** [comment]
Done in `master`.
