### ISSUE TITLE
Anonymous classes should not form part of a public API

### ISSUE THREAD

**Issue by Bilge** [amphp/http-client#160]
`DefaultClient::request()` returns a promise that yields an anonymous class. In a world of `Promise`s, for which return types cannot be hinted and type safety is often absent, having a promise that returns an anonymous class only exacerbates the problem. I opine it is never a good idea for any library to return anonymous classes because it precludes the consumer from opting into type safety at runtime and type hinting in their editor. Unless there's a very compelling reason to do this, I'd strongly recommend returning a concrete class in these cases, such as an `HttpResponse` class (or similar) for this particular method.

**Comment by kelunik** [comment]
@Bilge You can type hint the `Response` interface. But we might change it to `Internal\Response` anyway, because that's nicer with `var_dump`.

**Comment by kelunik** [comment]
Done in `master`.
