### ISSUE TITLE
Cookies without a domain causes errors in ArrayCookieJar

### ISSUE THREAD

**Issue by Bilge** [amphp/http-client#167]
```php
        $jar = new ArrayCookieJar;
        $jar->store(new Cookie('foo', 'bar'));
        $jar->get('baz');
```

>Uninitialized string offset: 0
vendor\amphp\artax\lib\Cookie\ArrayCookieJar.php:108

**Comment by kelunik** [comment]
Indeed. There's no backwards compatible way to fix that, but we could throw there.
