### ISSUE TITLE
$request->withHeader(); doesn't set the header.

### ISSUE THREAD

**Issue by MattiaBLX** [amphp/http-client#183]
$request is an instance of > \Amp\Artax\Request
`$request->withHeader("Content-Type", "application/x-www-form-urlencoded");` 
So the header should be set, but if I do `var_dump($request->getHeader("Content-Type");` it says "NULL"

**Comment by kelunik** [comment]
`Request` is immutable and returns a new instance, so you need `$request = $request->withHeader('content-type', 'application/x-www-form-urlencoded');`

**Comment by MattiaBLX** [comment]
Oh, ok. 
```
array(1) {
  ["content-type"]=>
  array(1) {
    [0]=>
    string(33) "application/x-www-form-urlencoded"
  }
}
```

It's ok that "application/x-www-form-urlencoded" is into an array?

**Comment by MattiaBLX** [comment]
Thank you for your help.
