### ISSUE TITLE
Making a request over HTTP2 with a FormBody throws

### ISSUE THREAD

**Issue by PeeHaa** [amphp/http-client#187]
```php
$request = new \Amp\Http\Client\Request('https://stackoverflow.com/users/login', 'POST');

$request->setBody(new \Amp\Http\Client\Body\FormBody());

$response = yield (new \Amp\Http\Client\Client)->request($request);
```

Results in the following exception:

> PHP Fatal error:  Uncaught Error: Amp\Http\Client\Connection\Internal\Http2Stream property "status" does not exist ... did you mean "state?" in D:\Web\amp-bot\stackoverflow-chat-driver\vendor\amphp\amp\lib\Struct.php:21
Stack trace:
#0 D:\Web\amp-bot\stackoverflow-chat-driver\vendor\amphp\http-client\src\Connection\Http2Connection.php(310): Amp\Http\Client\Connection\Internal\Http2Stream->__get('status')
#1 [internal function]: Amp\Http\Client\Connection\Http2Connection->Amp\Http\Client\Connection\{closure}()
#2 D:\Web\amp-bot\stackoverflow-chat-driver\vendor\amphp\amp\lib\Coroutine.php(105): Generator->send(NULL)
#3 D:\Web\amp-bot\stackoverflow-chat-driver\vendor\amphp\amp\lib\Success.php(36): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#4 D:\Web\amp-bot\stackoverflow-chat-driver\vendor\amphp\amp\lib\Coroutine.php(138): Amp\Success->onResolve(Object(Closure))
#5 D:\Web\amp-bot\stackoverflow-chat-driver\vendor\amphp\amp\lib\functions.php(66): Amp\Coroutine->__construct(Object(Generator))
#6 D:\Web\amp-bot\stackoverflow-chat-drive in D:\Web\amp-bot\stackoverflow-chat-driver\vendor\amphp\amp\lib\functions.php on line 184

**Comment by trowski** [comment]
Fixed in d957a184c3b143e622e80de29ccb52a7cf6e026b.
