### ISSUE TITLE
Cannot catch timeout exceptions

### ISSUE THREAD

**Issue by PeeHaa** [amphp/http-client#190]
```php
$request = new \Amp\Http\Client\Request('https://example.com');

$request->setTlsHandshakeTimeout(1);

try {
    yield (new \Amp\Http\Client\Client())->request($request);
} catch(\Amp\Http\Client\TimeoutException $e) {
    var_dump('\o/');
}
```

Still results in:

> PHP Fatal error:  Uncaught Amp\Http\Client\TimeoutException: TLS handshake with 'example.com:443' @ '93.184.216.34:443' timed out, took longer than 1 ms in D:\Web\amp-bot\wikipedia-plugin\vendor\amphp\http-client\src\Connection\DefaultConnectionPool.php:138
> Stack trace:
> #0 [internal function]: Amp\Http\Client\Connection\DefaultConnectionPool->Amp\Http\Client\Connection\{closure}()
> #1 D:\Web\amp-bot\wikipedia-plugin\vendor\amphp\amp\lib\Coroutine.php(102): Generator->throw(Object(Amp\CancelledException))
> #2 D:\Web\amp-bot\wikipedia-plugin\vendor\amphp\amp\lib\Failure.php(29): Amp\Coroutine->Amp\{closure}(Object(Amp\CancelledException), NULL)
> #3 D:\Web\amp-bot\wikipedia-plugin\vendor\amphp\amp\lib\Internal\Placeholder.php(125): Amp\Failure->onResolve(Object(Closure))
> #4 D:\Web\amp-bot\wikipedia-plugin\vendor\amphp\amp\lib\Internal\Placeholder.php(156): Amp\Coroutine->resolve(Object(Amp\Failure))
> #5 D:\Web\amp-bot\wikipedia-plugin\vendor\amphp\amp\lib\Coroutine.php(124): Amp\Coroutine->fail(Object(Amp\CancelledException))
> #6 D:\W in D:\Web\amp-bot\wikipedia-plugin\src\Plugin.php on line 78

**Comment by kelunik** [comment]
I cannot reproduce this behavior with the test above.

**Comment by PeeHaa** [comment]
You are correct. Both my repro was faulty as well as my assumption that I should see a sign of my own exception (I guess?)...

```php
$request = new \Amp\Http\Client\Request('https://example.com');

$request->setTlsHandshakeTimeout(1);

try {
    yield (new \Amp\Http\Client\Client())->request($request);
} catch(\Amp\Http\Client\TimeoutException $e) {
    throw new \Exception('My message', 0, $e);
}
```

The above code makes no reference to the custom thrown exception only the previous exception message which confused me.
