### ISSUE TITLE
Why is request no longer immutable?

### ISSUE THREAD

**Issue by prolic** [amphp/http-client#191]
As of v4.0 the request is no longer immutable. I'd love to the the immutability back again! What's the reason behind this?

**Comment by kelunik** [comment]
We wanted to add attributes to requests where we can't guarantee immutability and figured that streams are anyway mutable in response. Making request immutable but response not seemed bad. I'm open to reverting that change before the final release.

**Comment by prolic** [comment]
If you take a look at zend-diactoros f.e., the request and response are both immutable. I don't see much difference to this implementation, except that you return promises here and there.

**Comment by trowski** [comment]
The partial-immutability of PSR-7 leads to false assumptions. Most obvious is the stream being mutable — try reading a response stream twice and you'll run into problems. We are considering adding request attributes, similar to `http-server`, which could refer to mutable objects, leading to a quasi-immutable object.

Speaking of `http-server`, the `Request`/`Response` objects in that library are also mutable, so symmetry in `http-client` seemed to make sense.

IMO, immutability is best kept to simple objects containing scalar values (or perhaps amalgamations of other, truly immutable objects). Here's a short article that describes what I mean: [Avoiding Quasi-Immutable Objects in PHP](http://paul-m-jones.com/post/2016/09/06/avoiding-quasi-immutable-objects-in-php/).

**Comment by prolic** [comment]
Thanks for the clarification. I'm fine if you close this issue.
