### ISSUE TITLE
Authentication via URL is not working

### ISSUE THREAD

**Issue by enumag** [amphp/http-client#200]
```php
$url = 'http://bunny:password@127.0.0.1:15674/api/aliveness-test/%2F';

$guzzle = new \GuzzleHttp\Client();
$amphp = new \Amp\Http\Client\Client();

// 200
dump($guzzle->get($url)->getStatusCode());

// 401
dump((yield $amphp->request($url))->getStatus());

// 200
$request = new Request($url);
$request->addHeader('Authorization', 'Basic ' . base64_encode('bunny:password'));
dump((yield $amphp->request($request))->getStatus());

**Comment by enumag** [comment]
If this is a desired feature I can try to send a PR if you tell me where it should be handled.

**Comment by enumag** [comment]
I'm guessing it should be implemented as an interceptor which would check `$request->getUri()->getUserInfo()` and add it as header?

**Comment by kelunik** [comment]
@enumag That sounds like a good idea, yes.

**Comment by enumag** [comment]
Should such interceptor be default?

**Comment by trowski** [comment]
@enumag IMO the interceptor should be enabled by default. See #201 for how I propose doing something similar for following redirect responses.

**Comment by kelunik** [comment]
It should be enabled by default, but probably needs special support for redirects.
