### ISSUE TITLE
persistent HTTP connections example

### ISSUE THREAD

**Issue by chanonjang** [amphp/http-client#213]
Hello,

Can you make example for Pools persistent keep-alive connections ?

**Comment by kelunik** [comment]
Connections are reused by default, so any example in the example directory applies.

**Comment by chanonjang** [comment]
OK 
Thank you.

**Comment by trowski** [comment]
@kelunik We don't have an example that makes multiple requests to the same host, so no, none of the examples make use of this feature.

**Comment by chanonjang** [comment]
@trowski that's right
