### ISSUE TITLE
league/uri-interfaces ^2 should be supported in v4

### ISSUE THREAD

**Issue by ostrolucky** [amphp/http-client#214]

**Comment by trowski** [comment]
Need to wait on `league/uri-schemes@^2`

**Comment by ostrolucky** [comment]
Nah you don't need to bump requirement to > 2, just make sure it's compatible with 2 and change requirement to ^1|^2

**Comment by trowski** [comment]
There's no use in it being compatible with 2 unless `uri-schemes` has a release compatible with 2.

**Comment by kelunik** [comment]
Well, fixed. ;-)
