### ISSUE TITLE
Is there a way to track stats for requests?

### ISSUE THREAD

**Issue by duronrulez** [amphp/http-client#227]
Guzzle has the on_stats handler for this: http://docs.guzzlephp.org/en/stable/request-options.html#on-stats

Does the http client has something similar, i've tried digging around but i couldnt find anything.

**Comment by kelunik** [comment]
There's an event listener interface you can implement, see https://github.com/amphp/http-client/blob/master/src/Interceptor/LogHttpArchive.php for an example of combining interceptors with event listeners.

Which stats are you looking for specifically?

**Comment by duronrulez** [comment]
I will check that listener, thank you.
Right now im looking for measuring response time

**Comment by kelunik** [comment]
@duronrulez The response time can also be measured with interceptors.
