### ISSUE TITLE
Intercept calls are ignored

### ISSUE THREAD

**Issue by duronrulez** [amphp/http-client#228]
I have the following:
```
$builder = new HttpClientBuilder();
$builder->followRedirects(2);
$builder->intercept(new SetRequestTimeout(5000, 5000, 5000));
$builder->intercept(new LogHttpArchive("/tmp/test.txt"));
$builder->intercept(new SetRequestHeader('User-Agent', 'test'));
$builder->intercept(new SetRequestHeader('Accept-Encoding', 'gzip, deflate'));
        
$client = $builder->build();

..........

$request = new Request('myprivatehost');
$request->setBodySizeLimit(1024*1024*2);
$response = yield $client->request($request);
..........

```

Response is received fine, but none of the intercept classes are applied.
I've noticed they do get registered in the build loop (at least it seems so), but still not working.

I've verified that the user agent is missing by looking at my requested uri host logs, it uses the default amphp user agent.
I've verified that the http archiver doesnt work, by checking for existing /tmp/test.txt file, but there was none.

No exceptions are raised during runtime.

Any idea what i might be doing wrong?

**Comment by kelunik** [comment]
The builder always returns a new instance, so you need to rewrite it to:

```php
$client = (new HttpClientBuilder)
    ->followRedirects(2)
    ->intercept(new SetRequestTimeout(5000, 5000, 5000))
    ->intercept(new LogHttpArchive("/tmp/test.txt"))
    ->intercept(new SetRequestHeader('User-Agent', 'test'))
    ->intercept(new SetRequestHeader('Accept-Encoding', 'gzip, deflate'))
    ->build();
```
