### ISSUE TITLE
Request headers are lowercased

### ISSUE THREAD

**Issue by nicolas-grekas** [amphp/http-client#242]
Same as #164. On Symfony, we've got https://github.com/symfony/symfony/issues/32819 a few months ago.

TL;DR there *are* API servers that are case sensitive. Yes, this is not HTTP-compliant.
Yet, lowercasing the headers before sending them is not required.
We chose to *not* lowercase headers when sending them on HTTP/1.x so that the client can still consume those APIs.

I think the Amp client should reconsider and do the same. At least on Symfony's side, the current strict behavior means we're not sure if we can ship Amp's implementation as the default one (when it is installed).

**Comment by trowski** [comment]
We could consider adding `Request::getOriginalHeaderNames()` and `Response::getOriginalHeaderNames()` so the HTTP/1.x client can use/set those. Thoughts @kelunik?

**Comment by kelunik** [comment]
@nicolas-grekas Before we start implementing this, did you hear any other complaints or was that the only such request?

**Comment by nicolas-grekas** [comment]
That's the only report on the topic. But now that this is fixed, we won't get more...

**Comment by kelunik** [comment]
A related question is whether we want to support specific header ordering. I've stumbled upon this while implementing this in `Message`.

**Comment by nicolas-grekas** [comment]
> A related question is whether we want to support specific header ordering

Right now ordering is preserved for the first header of each kind, isn't it?
I think that's enough, no need for per header line order preservation.
