### ISSUE TITLE
How do I cancel an already accepted push promise?

### ISSUE THREAD

**Issue by nicolas-grekas** [amphp/http-client#243]
In my use case, I accept all HTTP/2 push promises and put them in a temporary cache.
After some time, I want to cancel the ones that have not been used yet.
I didn't find a way to do so, did I miss something?
Thanks for the help :)

**Comment by trowski** [comment]
You can throw a `Amp\CancelledException` or an `Amp\Http\Client\HttpException` from the push promise handler to cancel the push promise.

**Comment by nicolas-grekas** [comment]
> You can throw  from the push promise handler

I spotted that, but I'm not sure that answers my use case. Maybe it's me not being fluent enough with amp.
Inside the push handler, I store pushed req+response-promise in a queue.
Then, later on, I consume from the queue. And from time to time, I want to empty the queue.
Could the push handler be give a 3rd argument: a cancellation source that we could use to cancel the pushed req/resp when needed later on?

**Comment by trowski** [comment]
Funny you should suggest a cancellation token source as a third argument, since that's how I originally wrote that function. @kelunik I think we should add that back.
