### ISSUE TITLE
Promise already resolved error surfacing

### ISSUE THREAD

**Issue by danog** [amphp/http-client#244]
Using the latest tag, I've been getting a few promise already resolved exceptions: https://hastebin.com/yesocayehe.shell

**Comment by trowski** [comment]
Link appears to be broken, I only see a blank shell.

**Comment by danog** [comment]
welp hastebin seems down, try https://pastebin.com/ipcGavRE

**Comment by trowski** [comment]
Can you try with master and let me know if that resolves the issue?

**Comment by danog** [comment]
Everything OK so far, mind tagging?
