### ISSUE TITLE
Timeout when using ConnectionLimitingPool

### ISSUE THREAD

**Issue by nicolas-grekas** [amphp/http-client#256]
Sorry for the heavy reproducer - this happens on the Symfony test suite, see https://github.com/symfony/symfony/pull/35924#issuecomment-593897611 for details and reproducer.

**Comment by kelunik** [comment]
Tagged as https://github.com/amphp/http-client/releases/tag/v4.2.1.

**Comment by nicolas-grekas** [comment]
Thanks to the both of you!
