### ISSUE TITLE
PSR-7

### ISSUE THREAD

**Issue by enumag** [amphp/http-client#266]
Do you have / know about any existing implementation that would allow me to transform a [PSR-7](https://www.php-fig.org/psr/psr-7/) request into `Amp\Http\Client\Request` and later a `Amp\Http\Client\Response` into a PSR-7 response?

**Comment by kelunik** [comment]
I don't know about anything like that, but we could probably easily add it.

**Comment by nicolas-grekas** [comment]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpClient/Psr18Client.php

This will do the job and allow mapping this to that.
Note that PSR-7 is mostly not compatible with any async feature so there is little better you can do than use PSR-18.

**Comment by remorhaz** [comment]
That would be a nice feature, sometimes there's a need to pass messages to PSR-compatible code or receive it from it, and I have to implement adapters by myself. It's an easy task, but it's better to have it done by library.

**Comment by kelunik** [comment]
@remorhaz If you already have the code, a PR is welcome. ;-)

**Comment by remorhaz** [comment]
I guess it's better to implement it as a part of `amphp/http` (consider moving the issue). I will prepare the PR soon.

**Comment by remorhaz** [comment]
Oops, seems that `Message` class is too abstract, it doens't even contain a body. In this case let's move from particulars to generals.

**Comment by kelunik** [comment]
Yes, it needs to be implemented here instead.

**Comment by kelunik** [comment]
See https://github.com/amphp/http-client-psr7.
