### ISSUE TITLE
Loop exceptionally stopped + Trying to access offset on value of type null

### ISSUE THREAD

**Issue by duronrulez** [amphp/http-client#272]
using amphp/http-client: 4.4.0 and php 7.4.0

Reproducable script:
```
$builder = (new HttpClientBuilder);

        $client = $builder->build();

        $promise = call(
                function () use ($client) {
                    $url = 'https://samsung.com';

                    $request = new Request($url);
                    $response = yield $client->request($request);
                }
            );
        wait($promise);
```
Result:

```
Loop exceptionally stopped without resolving the promise {"exception":"[object] (Error(code: 0): Loop exceptionally stopped without resolving the promise at vendor/amphp/amp/lib/functions.php:232)
.....
[previous exception] [object] (ErrorException(code: 0): Trying to access array offset on value of type null at vendor/amphp/socket/src/Internal/functions.php:131)
[stacktrace]
```

I've also posted a similar issue in the amphp/socket repo, since the exception seems to be originating there: https://github.com/amphp/socket/issues/76

**Comment by kelunik** [comment]
It outputs a proper error message for me: `PHP Fatal error:  Uncaught Amp\Socket\TlsException: TLS negotiation failed: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small`. I guess it can be resolved by reducing the security level on the TLS context.

I've applied a patch to amphp/socket that should now report `Unknown error` to you if there's no available message.

**Comment by duronrulez** [comment]
Hm, thats weird, do you have any idea why i might be getting different results?

**Comment by kelunik** [comment]
Something like that might be the case, yes.

**Comment by duronrulez** [comment]
reducing the security level to 1 works, using OpenSSL 1.1.1d  10 Sep 2019
Now to figure out why i needed to reduce it :D

**Comment by kelunik** [comment]
@duronrulez This means we should probably switch to using an error handler instead of `error_get_last()`.

**Comment by duronrulez** [comment]
can confirm that if i put `restore_error_handler()` before the `stream_socket_enable_crypto()` call the error is being received in `error_get_last()`. In my case the handler is the default laravel exception handler: https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php

Obviously this doesn't solve anything, but at least i know whats breaking it.

**Comment by duronrulez** [comment]
Looks like its working 👍 
All 3 contained exceptions are now being reported properly and catchable.

Not sure what is the process exactly, but when do you think an update will be available?

**Comment by kelunik** [comment]
Tagged as [v1.1.3](https://github.com/amphp/socket/releases/tag/v1.1.3). ;-)
