### ISSUE TITLE
Incompatible with CookieInterceptor since 4.2.1

### ISSUE THREAD

**Issue by Bilge** [amphp/http-client#281]
A change introduced [between releases 4.2.0 and 4.2.1](https://github.com/amphp/http-client/compare/v4.2.0..v4.2.1) breaks the `CookieInterceptor`. May also affect other interceptors.

The specific usage scenario is: a PHPUnit test makes four HTTP calls in serial, one in each test (of the same test class). Then it makes an additional two HTTP calls in two different test case classes (one in each). Either one or both of these will typically fail (very rarely they might both pass, providing a false positive). The first four tests (in the same class) share the same connection pool and always pass. The next two tests create a new pool each, but share the same cookies, and often fail as described.

**Comment by kelunik** [comment]
Please share a simple script to reproduce the behavior you're seeing.

**Comment by Bilge** [comment]
Will be very tricky considering I cannot reproduce locally, only on Travis.

**Comment by Bilge** [comment]
For what it's worth, I validated my suspicion that [disabling pooling](https://github.com/Porter-connectors/HttpConnector/compare/no-pool) avoids the problem. Although I cannot provide a contrived test case at this point, this confirms to me that there is an invalid interaction between pooling and interceptors.

**Comment by kelunik** [comment]
@Bilge Do you use `--static-backup` in PHPUnit?

**Comment by Bilge** [comment]
No

**Comment by kelunik** [comment]
How do you ensure the cookies are shared correctly? Does one test create them and the other use them?

**Comment by Bilge** [comment]
Test base class statically initializes them. https://github.com/Provider/Steam/blob/69420587c3a09a7c1ac5d1378825a98f896471f1/test/FixtureFactory.php#L38-L54

**Comment by kelunik** [comment]
The issue is likely in your code somewhere, e.g. cloning the `CookieJar` could be problematic.

We can reopen the issue if you provide a simple reproduction case.
