### ISSUE TITLE
"Flood detected" exception in the client over HTTP/2

### ISSUE THREAD

**Issue by deadbeat88** [amphp/http-client#282]
I'm getting an exception here [Http2Parser.php:188](https://github.com/amphp/http/blob/06d3b914cbe79b7c66b0efbae4a6aca81a718429/src/Http2/Http2Parser.php#L188) in the http-client when I try to send a some concurrent requests.
The protection is designed for servers, so need something different for clients.

**Comment by kelunik** [comment]
Fixed in https://github.com/amphp/http/releases/tag/v1.6.3. Thanks!
