### ISSUE TITLE
Unable to request api.weibo.com

### ISSUE THREAD

**Issue by xpader** [amphp/http-client#283]
When request https://api.weibo.com, http-client throw exception:  `Can't set an application layer protocol list, as PHP is compiled with OpenSSL < 1.0.2.`
That's because my php(7.4.10) complied openssl is 1.0.1e.
But when I modify hasTlsAlpnSupport in function.php, everything works fine.
So, why do this check?

**Comment by kelunik** [comment]
@xpader We need to determine the support, because we believe software should be secure-by-default, but find the default security level to be too low. How did you modify `hasTlsAlpnSupport`? Would you like to send a PR?

**Comment by xpader** [comment]
@kelunik Uh.. I just change it to always return true...
```
/**
 * @see https://wiki.openssl.org/index.php/Manual:OPENSSL_VERSION_NUMBER(3)
 * @return bool
 */
function hasTlsAlpnSupport(): bool
{
    //return \defined('OPENSSL_VERSION_NUMBER') && \OPENSSL_VERSION_NUMBER >= 0x10002000;
    return true;
}
```
So it seems that the check is not necessary or accurate.

**Comment by kelunik** [comment]
@xpader If you look at `php --info | grep -i openssl`, what's `OpenSSL Library Version` / `OpenSSL Header Version`?

**Comment by kelunik** [comment]
@xpader Please try with the latest `master`.

**Comment by xpader** [comment]
@kelunik 

```
Configure Command =>  './configure'  '--prefix=/home/user/apps/php74' '--with-config-file-path=/home/user/apps/php74/etc' '--enable-mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql' '--with-mhash' '--with-openssl' '--with-curl' '--enable-mbstring' '--enable-bcmath' '--enable-sockets' '--enable-exif' '--without-iconv' '--with-freetype' '--with-bz2' '--with-sodium' '--enable-ftp' '--disable-rpath' '--without-pear' '--enable-inline-optimization' '--disable-cgi' '--with-layout=GNU' 'CPPFLAGS=' 'CPP=cpp' 'PKG_CONFIG_PATH=/home/user/apps/sqlite3/lib/pkgconfig:/home/user/apps/oniguruma/lib/pkgconfig:/home/user/apps/libsodium/lib/pkgconfig:/home/user/apps/readline/lib/pkgconfig'
openssl
Openssl default config => /etc/pki/tls/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by kelunik** [comment]
@xpader I noticed the runtime check only exists for the security level in php-src. Did you try with the lastest dev version?

**Comment by xpader** [comment]
@kelunik Yes, The commit https://github.com/amphp/http-client/commit/1c1f383758031938586402c4f148a053037a19a7 fixed for me. Thanks.

**Comment by kelunik** [comment]
Thanks for confirming, I've tagged a new release.
