### ISSUE TITLE
What is closed early with 0 bytes received?

### ISSUE THREAD

**Issue by xpader** [amphp/http-client#286]
I have a task running every minutes and have a lots of reqeust to c.api.weibo.com, but there's about 1%-10% error, the Exception is:

`Amp\Http\Client\SocketException: Receiving the response headers for 'https://c.api.weibo.com/2/statuses/destroy/biz.json?access_token=XXX' failed, because the socket to 'c.api.weibo.com' @ '180.149.134.96:443' closed early with 0 bytes received within 6000 milliseconds in /home/myproject/vendor/amphp/http-client/src/Connection/Http1Connection.php:494`

What is 'closed early with 0 bytes received'?

**Comment by kelunik** [comment]
This mean the connection closed without receiving any bytes from the server.

**Comment by xpader** [comment]
Is this mean "Read data timeout"?

**Comment by kelunik** [comment]
Yes.
