### ISSUE TITLE
Does \tempnam blocks event loop? (streaming example)

### ISSUE THREAD

**Issue by Guuzen** [amphp/http-client#288]
PHP docs states that "tempnam — Create file with unique file name" so looks like it is io operation.
https://github.com/amphp/http-client/blob/ac286c0a2bf1bf175b08aa89d3086d1e9be03985/examples/streaming/2-http1-http2.php#L42

**Comment by kelunik** [comment]
Yes, it's an IO operation, but usually very short. Depending on your application, this short blocking might be acceptable, but it obviously depends on the frequency with which you create such files.
