### ISSUE TITLE
Connection not being cleaned up after Loop

### ISSUE THREAD

**Issue by ThaDaVos** [amphp/http-client#289]
**Context**: We are using the `amphp/http-client` to connect to a Server Sent Events endpoint to listen for job completion - this is all done in a Background Job using the Laravel Framework. We are using the response streaming pattern as mentioned in the `amphp/http-client` documentation.

**Problem**: After listening it ending the `Loop::run()` it seems the connection won't be killed until the server stops sending data and even after that it seems to keep running. We noticed this by an increasing amount of PHP-FPM Workers being spawned.

**Question**: How do we fully close off the connection properly? We're currently trying to dispose it by first setting the `$response` and `$body` to `null` and then unsetting both by calling `unset($response)` and `unset($body)`. But the connection still seems to stay active.

**Environment**:
    PHP: 7.4
    Framework used: Laravel Framework 7.x

**Comment by kelunik** [comment]
I'd recommend passing a cancellation token as second parameter and using the cancellation to cancel the response once you are no longer interested.

**Comment by ThaDaVos** [comment]
Thanks, will try that on Monday - never thought that would be possible with the `amphp/http-client` package...
