### ISSUE TITLE
Receiving the response headers for ** closed early 

### ISSUE THREAD

**Issue by PNixx** [amphp/http-client#291]
In high load http send data to server I see errors in log:
```
[2021-05-06T13:24:25.112194+03:00] Amp\Http\Client\SocketException: Receiving the response headers for 'https://cache.example.com/1515915625626368448-6093c3ad148e9.html.gz' failed, because the socket to 'cache.example.com' @ '???' closed early with 0 bytes received within 29557 milliseconds
```
But in nginx log I see `201` response code:
```
12.3.4.10 - [06/May/2021:13:23:55 +0300] "PUT /1515915625626368448-6093c3ad148e9.html.gz HTTP/1.1" 201 0 "-" "User Cacher 2.0" "-" 0.001
```
Response time `0.001` sec.

**Comment by kelunik** [comment]
Which event loop backend do you use? How many concurrent connections are high load?

**Comment by PNixx** [comment]
I use rabbit with Prefetch count = 30. All received messages uploading html cache to server. And I see similar error:
```
Amp\Http\Client\TimeoutException, Inactivity timeout exceeded, more than 5000 ms elapsed from last data received
```
But file is correctly upload to server. For now, I just ignore these errors to keep the code running. But this is very bad behavior.

**Comment by kelunik** [comment]
Please report what `var_dump(get_class(Loop::get()))` says. Did you try to write a smaller script doing something similar to reproduce the issue?

**Comment by kelunik** [comment]
I'm aware of issues with older Nginx instances not closing HTTP/2 connections correctly, which results in similar behavior, but I'm not aware of any such issues with HTTP/1.1. Without further information such as reproduction steps, it'll be hard to reproduce this issue, so I'm closing this until there's further information.

**Comment by xpader** [comment]
I saw this error everyday in logs:
```
Amp\Http\Client\SocketException: Receiving the response headers for 'https://api.example.com/xxx?access_token=xxx' failed, because the socket to 'api.example.com' @ '1.2.3.4:443' closed early with 0 bytes received within 0 milliseconds in /home/web/apps/t-task-wind/releases/94/vendor/amphp/http-client/src/Connection/Http1Connection.php:494
Stack trace:
#0 /home/web/apps/t-task-wind/releases/94/vendor/amphp/http-client/src/Connection/Http1Connection.php(235): Amp\Http\Client\Connection\Http1Connection->readResponse()^M
#1 [internal function]: Amp\Http\Client\Connection\Http1Connection->Amp\Http\Client\Connection\{closure}()
#2 /home/web/apps/t-task-wind/releases/94/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#3 /home/web/apps/t-task-wind/releases/94/vendor/amphp/amp/lib/Internal/Placeholder.php(46): Amp\Coroutine->Amp\{closure}()
#4 /home/web/apps/t-task-wind/releases/94/vendor/amphp/amp/lib/Coroutine.php(151): Amp\Coroutine->onResolve()
```

**Comment by xpader** [comment]
I think this is strange.
The request to https://api.example.com we test in browser is always http2 connection, but the reported exception was from Http1Connection.

**Comment by kelunik** [comment]
@xpader In that case you'll need to debug why the connection isn't upgraded. Does it work with HTTP 1.1 with other clients?

**Comment by xpader** [comment]
@kelunik May be it cause I have use http proxy by [http-client-tunnel](https://github.com/amphp/http-tunnel), target host is http2, but proxy server is http1.1?
