### ISSUE TITLE
fopen('php:://stdout') operation fail

### ISSUE THREAD

**Issue by mztlive** [amphp/http-client#294]
FastCGI sent in stderr: "PHP message: PHP Warning:  fopen(php://stdout): failed to open stream: operation failed in /data/wwwroot/*******/vendor/amphp/byte-stream/lib/functions.php on line 19PHP message: PHP Warning:  fopen(php://stderr): failed to open stream: operation failed in /data/wwwroot/******/vendor/amphp/byte-stream/lib/functions.php on line 23" while reading response header from upstream, client: ******, server: *****, request: "POST /groupon/user/isStudent HTTP/1.1", upstream: "fastcgi://*****:9002", host: "*****"

What is the reason?

**Comment by kelunik** [comment]
We try to open STDOUT / STDERR if they're not defined, seems like STDOUT is available with your setup but STDERR is not? https://github.com/amphp/byte-stream/blob/7a64a9ad336fc5e1e70b1c1fc1e9618a7027332e/lib/functions.php#L23

**Comment by mztlive** [comment]
> We try to open STDOUT / STDERR if they're not defined, seems like STDOUT is available with your setup but STDERR is not? https://github.com/amphp/byte-stream/blob/7a64a9ad336fc5e1e70b1c1fc1e9618a7027332e/lib/functions.php#L23

Neither fopen(php://stdout) and fopen(php://stderr)  nor  support. 
This happened during performance testing

**Comment by kelunik** [comment]
Could you build a docker image to reproduce the issue?
