### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Tatikoma** [amphp/http-client#300]
Http1Connection.php:217
```
$combinedCancellation = new CombinedCancellationToken($cancellation, $timeoutToken);
```

This code creates subscriptions that should be canceled when the object is destroyed, however the object is never destroyed.

Dirty workaround:
```
$request->setTransferTimeout(0);
```

Latest versions of PHP 8.1, libuv, amphp.

How to reproduce:
1. Copy any example of using http-client.
2. dont use setTransferTimeout, or use value greater than 0.
3. add var_dump to CombinedCancellationToken::__destruct.
4. process should continue running after executing request
5. __destruct never called, no var_dump displayed.

**Comment by trowski** [comment]
Hi @Tatikoma,

Thanks for reporting this! This was recently fixed in https://github.com/amphp/amp/pull/384, which I just tagged as [amphp/amp v2.6.2](https://github.com/amphp/amp/releases/tag/v2.6.2). Please update and try again and reopen this issue if the problem persists.
