### ISSUE TITLE
BC break: v5 `Request::setBody` should accept `null`

### ISSUE THREAD

**Issue by Bilge** [amphp/http-client#307]
v5 `Request::setBody` should accept `null` because it did in v4. Also, WTF is up with `int` and `float`?

https://github.com/amphp/http-client/blob/92b60c132de57708a0255bdf05e9b2974f4a5047/src/Request.php#L222-L230

**Comment by kelunik** [comment]
It does accept null in #322. Please provide any feedback regarding the body API there.

**Comment by Bilge** [comment]
I really don't think it does, brotherman.

https://github.com/amphp/http-client/pull/322/files#diff-74d71c4d1f9d84b9b0d946ca96eb875274f95d60611611d84cc01cdf6ed04021R230-R233
