### ISSUE TITLE
I want to pass ReadableStream to FileBody

### ISSUE THREAD

**Issue by PhantomArt** [amphp/http-client#315]
In my code, I have the content of the file as a `ReadableStream`. I would like to create a `FileBody` from this `ReadableStream`. Right now I have two ways:

1. Save `ReadableStream` to a file on disk, then pass it to `FileBody`.
2. Read `ReadableStream` into a variable and pass it to `FileBody`.

It seems to me that both options are not optimal. `FileBody` is essentially an intermediary to supply a `ReadableStream` using the `createBodyStream()` method, so why isn't it possible to pass a `ReadableStream` directly to `FileBody`?

**Comment by PhantomArt** [comment]
I think I came up with a better version. You can create a `FormBody::addFileFromStream()` method that takes a `StreamBody` as an argument, similar to the `FormBody::addFileFromString()` method.

**Comment by kelunik** [comment]
This will be possible in 5.x, see #322.
