### ISSUE TITLE
Getting always Fatal error: Uncaught Error: ...

### ISSUE THREAD

**Issue by osworx** [amphp/http-client#316]
Maybe I have overseen something, or missed, or being too stupid for that.

Using latest version of amphp with php 8.2.0 (in a local environement called XAMPP).
No matter what I try, getting only errors.

1. Loaded all amphp files as stated in the manual by
`composer require amphp/http-client`

2. created a package of the files
3. created a new folder in the local server
4. created a new index.php with content (as displayed here https://github.com/amphp/http-client#interceptors):

```<?php
use Amp\Http\Client\Client;
use Amp\Http\Client\HttpClientBuilder;
use Amp\Http\Client\Interceptor\SetRequestHeader;
use Amp\Http\Client\Interceptor\SetResponseHeader;
use Amp\Http\Client\Request;

require 'system/storage/vendor/amphp/autoload.php';

$client = (new HttpClientBuilder)
    ->intercept(new SetRequestHeader('x-foo', 'bar'))
    ->intercept(new SetResponseHeader('x-tea', 'now'))
    ->build();

$response = $client->request(new Request("https://httpbin.org/get"));
$body = $response->getBody()->buffer();
```

Calling the index.php via the browser, all I get is that:
**Fatal error: Uncaught Error: Call to undefined method Amp\Coroutine::getBody() in ..\index-amp.php:24 Stack trace: #0 {main} thrown in ..\index-amp.php on line 24**

**Example 2**

Using now
```
use Amp\Http\Client\HttpClientBuilder;

require 'system/storage/vendor/amphp/autoload.php';

$client = HttpClientBuilder::buildDefault();

$response = $client->request(new Request("https://httpbin.org/get"));

var_dump($response->getStatus());
var_dump($response->getHeaders());
var_dump($response->getBody()->buffer());
```

gives me: 
**Fatal error: Uncaught Error: Class "Request" not found .. etc. ..**

All what I want is a working sample to embed the script to call external resources (rss-feeds) and fetch that content to store locally.
_Either I am missing something, make something wrong or that whole thing does not work with php 8.2.x_

**Comment by kelunik** [comment]
The code samples you're using are for version 5.x, while you probably installed version 4.x, as 5.x doesn't have a stable release, yet.

**Comment by osworx** [comment]
Well. thanks for the quick response.
But what I shall do to get a working solution?

**Comment by kelunik** [comment]
Have a look at the 4.x branch and its README and `docs` directory: https://github.com/amphp/http-client/tree/4.x
