### ISSUE TITLE
is latest version (4.6.2) imcompatible with latest amphp/amp (3) version?

### ISSUE THREAD

**Issue by arashnz** [amphp/http-client#318]
Hello,

I installed latest version of amp using composer, and composer created this line in my composer.json file:
        "amphp/amp": "^3.0"
Now, i want to install latest version of amp/http-client and i receive this error:

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires amphp/http-client ^4.6 -> satisfiable by amphp/http-client[v4.6.0, v4.6.1, v4.6.2].
    - amphp/http-client[v4.6.0, ..., v4.6.2] require amphp/amp ^2.4 -> found amphp/amp[v2.4.0, ..., v2.6.2] but it conflicts with your root composer.json require (^3.0).

how can i solve this problem?

**Comment by enumag** [comment]
No, for now only the 5.x dev version is compatible with amphp 3. You can use this:
```
"amphp/http-client": "^5.0@beta",
```

**Comment by arashnz** [comment]
is this release stable?
can i use older versions?

seems latest compatible stable release is v0.7.1 that i know have some serious bugs

**Comment by kelunik** [comment]
Not sure where you found 0.7.1. 4.x is the latest stable version compatible with amphp/amp 2.x. If you want to use amphp/amp 3.x, you have to use the beta versions which are not stable, yet.
