### ISSUE TITLE
Class "Amp\Http\Rfc7230" not found

### ISSUE THREAD

**Issue by xcgu** [amphp/http-client#321]
Hi

It seems there is a problem in the latest version of amp http-client

Class "Amp\Http\Rfc7230" not found in /var/www/html/dir/vendor/amphp/http-client/src/Connection/Http1Connection.php:667

**Comment by Bilge** [comment]
Yes https://github.com/ScriptFUSION/Porter/actions/runs/4529264734/jobs/7976828486

**Comment by xtrime-ru** [comment]
You should use tagged beta versions only. 
Latest dev versions not compatable yet.

Check example of my composer.json:

https://github.com/xtrime-ru/TelegramRSS/blob/v4/composer.json

Main part:
```
 "prefer-stable": true,
 "minimum-stability": "dev", 
```
