### ISSUE TITLE
If a response redirects, it sends back raw gzip instead of decoded content

### ISSUE THREAD

**Issue by Bilge** [amphp/http-client#332]
Somewhere between beta 9 and 11, but probably in beta 11, redirects cause raw gzip instead of decoded content to be emitted in the body.

```php
$client = HttpClientBuilder::buildDefault();
$response = $client->request(new Request('https://steamcommunity.com/profiles/76561197960287930')); // redirects
$body = $response->getBody()->read(); // gzip
```

```php
$client = HttpClientBuilder::buildDefault();
$response = $client->request(new Request('https://steamcommunity.com/id/GabeLoganNewell/')); // canonical URL (doesn't redirect)
$body = $response->getBody()->read(); // HTML
```

**Comment by kelunik** [comment]
This is caused by `FollowRedirects` and `DecompressResponse` interaction. `FollowRedirects` copies the headers to the new request. `DecompressResponse` then thinks the application set the header, so it skips doing anything.
