### ISSUE TITLE
Beta 11 encodes repeated form fields differently

### ISSUE THREAD

**Issue by Bilge** [amphp/http-client#340]
### Working 🏷️ v5.0.0-beta.7
`listid=110075&appids%5B0%5D=30&appids%5B1%5D=20`

### Busted 🏷️ v5.0.0-beta.12
`listid=110074&appids=30&appids=20`

**Comment by kelunik** [comment]
Indeed, this is by design, but isn't present in the changelog, yet.

**Comment by kelunik** [comment]
It's now documented in the beta 11 release notes.
