### ISSUE TITLE
4.x's php version depends changed because of league/uri

### ISSUE THREAD

**Issue by xpader** [amphp/http-client#344]
amphp/http-client depends on `league/uri:^6`, but `league/uri` from version 6.0 to 6.8 changed required php version depends from 7.2 up to 8.1 now.
This break `amphp 2.x` and `http-client 4.x` minimal php version >=7.2 required.
I think amphp/http-client should required league/uri as `league/uri:~6.4.0` to solve this problem.

**Comment by kelunik** [comment]
> I think amphp/http-client should required league/uri as `league/uri:~6.4.0` to solve this problem.

Composer will automatically use the older version if you use older versions of PHP, so newer versions requiring a newer version of PHP isn't a problem.

If you generate a `composer.lock` file on a newer version of PHP and then use that to deploy to older versions, that's a problem on your end. Either use the same version locally and on production or configure Composer with a specific platform version: https://stackoverflow.com/a/54736948/2373138

**Comment by xpader** [comment]
> > I think amphp/http-client should required league/uri as `league/uri:~6.4.0` to solve this problem.
> 
> Composer will automatically use the older version if you use older versions of PHP, so newer versions requiring a newer version of PHP isn't a problem.
> 

Thanks, I think I know what's going on here, I update some pack with `--ignore-platform-reqs`, so some package depends on newest PHP version is also upgraded.
