### ISSUE TITLE
Amp\Http\Client\TimeoutException: Allowed transfer timeout exceeded, took longer than 10 s in /home/madeline/vendor/amphp/http-client/src/Connection/Internal/Http2ConnectionProcessor.php:1562

### ISSUE THREAD

**Issue by Balanceuuiii** [amphp/http-client#348]
Amp\Http\Client\TimeoutException: Allowed transfer timeout exceeded, took longer than 10 s in /home/madeline/vendor/amphp/http-client/src/Connection/Internal/Http2ConnectionProcessor.php:1562
Stack trace:
#0 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(593): Amp\Http\Client\Connection\Internal\Http2ConnectionProcessor->Amp\Http\Client\Connection\Internal\{closure}()
#1 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#2 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(54): Fiber->resume()
#3 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(422): Revolt\EventLoop\Internal\DriverSuspension::Revolt\EventLoop\Internal\{closure}()
#4 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(612): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#5 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#6 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(494): Fiber->resume()
#7 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(549): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
#8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#9 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(93): Fiber->resume()
#10 /home/madeline/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(99): Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#11 /home/madeline/vendor/amphp/amp/src/Internal/FutureIterator.php(133): Revolt\EventLoop\Internal\DriverSuspension->suspend()
#12 /home/madeline/vendor/amphp/amp/src/Future.php(59): Amp\Internal\FutureIterator->consume()
#13 /home/madeline/vendor/amphp/amp/src/Future/functions.php(26): Amp\Future::iterate()
#14 /home/madeline/vendor/danog/madelineproto/src/API.php(465): Amp\Future\awaitFirst()
#15 /home/madeline/core/client.php(908): danog\MadelineProto\API::startAndLoopMulti()
#16 {main}

**Comment by kelunik** [comment]
@Balanceuuiii What's your exact question?
