### ISSUE TITLE
Support proxy authentication

### ISSUE THREAD

**Issue by rdlowrey** [amphp/http-client#73]
Currently there is no means to support `Proxy-Authorization:` headers ... needs to be fixed :)

**Comment by Bilge** [comment]
Confirmed, also needs supporting in `HTTP_PROXY`/`HTTPS_PROXY` environment fields.

**Comment by kelunik** [comment]
Those are already supported, but only in CLI mode, because Httpoxy.

**Comment by Bilge** [comment]
They do not support authentication.

**Comment by kelunik** [comment]
Built-in proxy support will probably not be part of 4.0 and can be implemented independently via the `Connector` interface.

**Comment by Bilge** [comment]
Do you mean proxy *authentication* will not be part of 4.0, or are you completely stripping out all proxy support in 4.0?

**Comment by kelunik** [comment]
We completely removed it for now, can be reimplemented using a `Connector`.

**Comment by Bilge** [comment]
You could completely remove the library and it be reimplemented by coding everything from scratch, but that assurance doesn't grant much comfort. Though I don't know your reasons for removing proxy support, it seems an incorrect decision.

**Comment by kelunik** [comment]
I don't care about proxy support and the previous implementation had a very sub-optimal API compared to the new socket Connector interface and didn't have any tests. Things that are more important to me are e.g. HTTP/2 and caching.

If you care for HTTP connect proxy support, please open a PR to the socket library turning the previous HttpTunnler into a Connector and include tests for it.
